apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: netobserv
spec:
  version: "{{ .TagName }}"
  homepage: https://github.com/netobserv/network-observability-cli
  shortDescription: "Lightweight Flow and Packet visualization tool"
  description: |
    Deploys NetObserv eBPF agent on your k8s cluster to collect flows 
    or packets from nodes network interfaces and streams data to a local 
    collector for analysis and visualization. 
  platforms:
  - selector:
      matchExpressions:
      - key: "os"
        operator: "In"
        values:
        - darwin
        - linux
    {{addURIAndSha ""https://github.com/netobserv/network-observability-cli/releases/download/{{ .TagName }}/netobserv-cli.tar.gz"" .TagName }}
    files:
    - from: "build/netobserv"
      to: "netobserv"
    - from: "LICENSE"
      to: "."
    bin: netobserv