apiVersion: v1
kind: Service
metadata:
  name: collector
  namespace: "{{NAMESPACE}}"
spec:
  selector:
    run: collector
  ports:
  - name: collector
    protocol: TCP
    port: 9999
    targetPort: 9999