apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: netobserv-cli
  namespace: netobserv-cli
  labels:
    app: netobserv-cli
spec:
  selector:
    matchLabels:
      app: netobserv-cli
  template:
    metadata:
      labels:
        app: netobserv-cli
    spec:
      serviceAccountName: netobserv-cli
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: netobserv-cli
        # image: quay.io/netobserv/netobserv-ebpf-agent:main
        image: quay.io/jpinsonn/netobserv-ebpf-agent:grpc
        imagePullPolicy: Always
        securityContext:
          privileged: true
          runAsUser: 0
        env:
          - name: METRICS_ENABLE
            value: "false"
          - name: LOG_LEVEL
            value: trace
          - name: INTERFACES
            value: "{{FLOW_FILTER_VALUE}}"
          - name: EXCLUDE_INTERFACES
            value: "lo"
          - name: SAMPLING
            value: "1"
          - name: ENABLE_RTT
            value: "true"
          - name: ENABLE_PKT_DROPS
            value: "true"
          - name: ENABLE_DNS_TRACKING
            value: "true"
          - name: EXPORT
            value: "direct-flp"
          - name: FLP_CONFIG
            value: >
              {
                "log-level": "trace",
                "metricsSettings":{
                    "disableGlobalServer": true
                },
                "parameters":[
                    {
                      "name":"enrich",
                      "transform":{
                          "type":"network",
                          "network":{
                            "rules":[
                                {
                                  "input":"SrcAddr",
                                  "output":"SrcK8S",
                                  "type":"add_kubernetes",
                                  "kubernetes":{
                                      "add_zone": true
                                  }
                                },
                                {
                                  "input":"DstAddr",
                                  "output":"DstK8S",
                                  "type":"add_kubernetes",
                                  "kubernetes":{
                                      "add_zone": true
                                  }
                                },
                                {
                                  "type":"reinterpret_direction"
                                },
                                {
                                  "type":"add_kubernetes_infra",
                                  "kubernetes_infra":{
                                      "inputs":[
                                        "SrcAddr",
                                        "DstAddr"
                                      ],
                                      "output":"K8S_FlowLayer",
                                      "infra_prefixes":"netobserv"
                                  }
                                }
                            ],
                            "directionInfo":{
                                "reporterIPField":"AgentIP",
                                "srcHostField":"SrcK8S_HostIP",
                                "dstHostField":"DstK8S_HostIP",
                                "flowDirectionField":"FlowDirection",
                                "ifDirectionField":"IfDirection"
                            }
                          }
                      }
                    },
                    {
                      "name":"send",
                      "write":{
                          "type":"grpc",
                          "grpc":{
                            "targetHost":"collector.netobserv-cli.svc.cluster.local",
                            "targetPort":9999
                          }
                      }
                    }
                ],
                "pipeline":[
                    {
                      "name":"enrich",
                      "follows":"preset-ingester"
                    },
                    {
                      "name":"send",
                      "follows":"enrich"
                    }
                ],
              }
        volumeMounts:
            - name: bpf-kernel-debug
              mountPath: /sys/kernel/debug
              mountPropagation: Bidirectional
      volumes:
        - name: bpf-kernel-debug
          hostPath:
            path: /sys/kernel/debug
            type: Directory
