apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: netobserv-cli
  namespace: "{{NAMESPACE}}"
  labels:
    app: netobserv-cli
spec:
  selector:
    matchLabels:
      app: netobserv-cli
  template:
    metadata:
      labels:
        app: netobserv-cli
    spec:
      serviceAccountName: netobserv-cli
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
      - operator: Exists
      containers:
      - name: netobserv-cli
        image: "{{AGENT_IMAGE_URL}}"
        imagePullPolicy: Always
        securityContext:
          privileged: true
          runAsUser: 0
        env:
          - name: METRICS_ENABLE
            value: "false"
          - name: LOG_LEVEL
            value: info
          - name: FLOW_FILTER_RULES
            value: >-
              []
          - name: EXPORT
            value: "direct-flp"
          - name: FLP_CONFIG
            value: |
              {}
        ports:
        - name: prometheus
          containerPort: 9401
          protocol: TCP
        volumeMounts:
            - name: bpf-kernel-debug
              mountPath: /sys/kernel/debug
              mountPropagation: Bidirectional
            - name: var-run-ovn
              mountPath: /var/run/ovn
              mountPropagation: Bidirectional
            - name: var-run-ovs
              mountPath: /var/run/openvswitch
              mountPropagation: Bidirectional
      volumes:
        - name: bpf-kernel-debug
          hostPath:
            path: /sys/kernel/debug
            type: Directory
        - name: var-run-ovn
          hostPath:
            path: /var/run/ovn-ic
            type: DirectoryOrCreate
        - name: var-run-ovs
          hostPath:
            path: /var/run/openvswitch
            type: DirectoryOrCreate
---
kind: Service
apiVersion: v1
metadata:
  name: netobserv-cli
  namespace: "{{NAMESPACE}}"
  labels:
    app: netobserv-cli
spec:
  ports:
    - name: prometheus
      protocol: TCP
      port: 9401
      targetPort: 9401
  selector:
    app: netobserv-cli
  type: ClusterIP