apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: netobserv-cli
  namespace: netobserv-cli
  labels:
    app: netobserv-cli
spec:
  selector:
    matchLabels:
      app: netobserv-cli
  template:
    metadata:
      labels:
        app: netobserv-cli
    spec:
      serviceAccountName: netobserv-cli
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: netobserv-cli
        # image: quay.io/netobserv/netobserv-ebpf-agent:main
        image: quay.io/jpinsonn/netobserv-ebpf-agent:grpc
        imagePullPolicy: Always
        securityContext:
          privileged: true
          runAsUser: 0
        env:
          - name: METRICS_ENABLE
            value: "false"
          - name: LOG_LEVEL
            value: trace
          - name: ENABLE_PCA
            value: "true"
          - name: PCA_FILTER
            value: "{{PCA_FILTER_VALUE}}"
          - name: FLOWS_TARGET_HOST
            value: "collector.netobserv-cli.svc.cluster.local"
          - name: FLOWS_TARGET_PORT
            value: "9999"
          - name: EXPORT
            value: "grpc"
