apiVersion: v1
kind: ServiceAccount
metadata:
  name: netobserv-cli
  namespace: netobserv-cli
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: netobserv-cli
  namespace: netobserv-cli
rules:
# allow running in privileged
  - apiGroups:
     - security.openshift.io
    resourceNames:
     - privileged
    resources:
     - securitycontextconstraints
    verbs:
     - use
# allow agents deletion from collector
  - apiGroups:
     - apps
    resources:
     - daemonsets
    verbs:
     - list
     - get
     - watch
     - delete
# allow pipeline enrichment
  - apiGroups:
     - ''
    resources:
     - pods
     - services
     - nodes
    verbs:
     - list
     - get
     - watch
  - apiGroups:
     - apps
    resources:
     - replicasets
    verbs:
     - list
     - get
     - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: netobserv-cli
  namespace: netobserv-cli
subjects:
  - kind: ServiceAccount
    name: netobserv-cli
    namespace: netobserv-cli
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: netobserv-cli
