apiVersion: v1
kind: ServiceAccount
metadata:
  name: netobserv-cli
  namespace: netobserv-cli
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: netobserv-cli
  namespace: netobserv-cli
rules:
  - apiGroups:
     - security.openshift.io
    resourceNames:
     - privileged
    resources:
     - securitycontextconstraints
    verbs:
     - use
  - verbs:
     - list
     - get
     - watch
    apiGroups:
     - ''
    resources:
     - pods
     - services
     - nodes
  - verbs:
     - list
     - get
     - watch
    apiGroups:
     - apps
    resources:
     - replicasets
  - verbs:
     - create
     - delete
     - patch
     - update
     - get
     - watch
     - list
    apiGroups:
     - autoscaling
    resources:
     - horizontalpodautoscalers
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: netobserv-cli
  namespace: netobserv-cli
subjects:
  - kind: ServiceAccount
    name: netobserv-cli
    namespace: netobserv-cli
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: netobserv-cli
