apiVersion: v1
kind: Namespace
metadata:
  name: gotls-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotls-test
  namespace: gotls-test
  labels:
    app: gotls-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gotls-test
  template:
    metadata:
      labels:
        app: gotls-test
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        hostUsers: false
      containers:
        - name: server
          image: __GOTLS_TEST_IMAGE__
          imagePullPolicy: __IMAGE_PULL_POLICY__
          ports:
            - name: https
              containerPort: 8443
          readinessProbe:
            httpGet:
              path: /healthz
              port: https
              scheme: HTTPS
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: https
              scheme: HTTPS
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop: ["ALL"]
---
apiVersion: v1
kind: Service
metadata:
  name: gotls-test
  namespace: gotls-test
spec:
  selector:
    app: gotls-test
  ports:
    - name: https
      port: 8443
      targetPort: https
